import { form, get, route } from 'remix/routes'

export const routes = route({
  assets: get('/assets/*path'),
  home: '/',
  libraryAlbums: '/library/albums',
  libraryAlbum: '/library/albums/:albumKey',
  libraryArtists: '/library/artists',
  libraryArtist: '/library/artists/:artistKey',
  libraryTracks: '/library/tracks',
  setup: form('/setup'),
  login: form('/login'),
  logout: { method: 'POST', pattern: '/logout' },
  playlists: form('/playlists'),
  playlist: form('/playlists/:id'),
  nowPlaying: '/now-playing',
  search: get('/search'),
  invites: form('/invites'),
  inviteRevoke: { method: 'POST', pattern: '/invites/:id/revoke' },
  join: form('/join/:token'),
  settings: form('/settings'),
  memberPromote: { method: 'POST', pattern: '/settings/members/:id/promote' },
  memberDemote: { method: 'POST', pattern: '/settings/members/:id/demote' },
  memberDisable: { method: 'POST', pattern: '/settings/members/:id/disable' },
  memberEnable: { method: 'POST', pattern: '/settings/members/:id/enable' },
  memberHardDelete: { method: 'POST', pattern: '/settings/members/:id/hard-delete' },
  memberTemporaryPassword: { method: 'POST', pattern: '/settings/members/:id/temporary-password' },
  scanNow: { method: 'POST', pattern: '/settings/scan' },
  session: { method: 'POST', pattern: '/session' },
  mediaTrack: get('/media/tracks/:trackId'),
})
